# curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -
[env]
# for underdotted and undercurl
TERM="alacritty"

[bell]
duration = 0

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1c1b1e"
foreground = "#d8dee9"

[font]
builtin_box_drawing = true
# normal.family = "IosevkaZeng"
# normal.style = "Light"
# size = 13
# CaskaydiaMono
# normal.family = "CaskaydiaMono"
# normal.style = "SemiLight"
# bold.style = "SemiBold"
# size = 12
# UbuntuSansMono
# normal.family = "UbuntuSansMono"
# size = 12
# jetbrains
# normal.family = "JetBrains"
# size = 11
# normal.style = "Light"
# SauceCodePro
# normal.family = "ConsolasNF"
# normal.family = "RobotoMono Nerd Font"
# size = 12
# normal.family = "SauceCodePro"
# size = 11.5
# normal.family = "ComicMono"
# size = 12.5
normal.family = "LilexNF"
size = 11
# normal.family = "Meslo"
# italic.family = "LilexNF"

[font.offset]
y = 0

[[keyboard.bindings]]
action = "ScrollLineUp"
mods = "Control|Shift"
key = "K"

[[keyboard.bindings]]
action = "ScrollLineDown"
mods = "Control|Shift"
key = "J"

[[keyboard.bindings]]
action = "Paste"
mods = "Shift"
key = "Insert"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
# use key binding or shift+leftMouse to open url
binding = { key = "`", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "tmux"
# force tmux assume terminal supports 256 colours
args = ["-2"]

[window]
decorations = "None"
dynamic_title = false
opacity = 0.99
startup_mode = "Maximized"
dynamic_padding = true

[scrolling]
history = 100000
