# curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -
[bell]
duration = 0

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#212529"
foreground = "#d8dee9"


[font.normal]
# family = "HackZeroSlash NerdFont"
family = "UbuntuMono NerdFont"
# family = "Monaco NerdFont"
# family = "ComicShannsMono NerdFont"
# family = "MesloLGS NerdFont"
# family = "BlexMono NerdFont"
# family = "Jetbrains Mono NF"
# family = "FiraCode NF"
# family = "Menlo Nerd Font"
# style = "Medium"

[font]
size = 15.0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/fish"

[window]
decorations = "none"
dynamic_title = false
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

