# get alacritty info
# curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -
window:
  opacity: 0.99
  decorations: none
  startup_mode: Windowed
  dynamic_title: true
  history: 20000
font:
  ligatures: false
  normal:
    # family: 'JetbrainsMono NF'
    # family: 'Hack NerdFont'
    family: 'HackZeroSlash NerdFont'
    # family: 'MesloLGM NerdFont'
    # family: 'MesloLGS NerdFont'
    # family: 'SFMono NerdFont'
    # family: 'OxygenMono NerdFont'
    # family: 'UbuntuMono NerdFont'
    # family: 'CommitMono NerdFont'
  size: 12.0
colors:
  primary:
    background: '#212529'
    foreground: '#d8dee9'
shell:
  program: /usr/bin/fish
bell:
  duration: 0
mouse:
  hide_when_typing: true
key_bindings:
  - { key: T, mods: Control|Shift, action: SpawnNewInstance }
  - { key: K, mods: Control|Shift, action: Quit }
