# curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -
[bell]
duration = 0

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#212529"
foreground = "#d8dee9"


[font.normal]
family = "UbuntuSansMono Nerd Font"

[font]
size = 12.0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ScrollLineUp"
mods = "Control|Shift"
key = "K"

[[keyboard.bindings]]
action = "ScrollLineDown"
mods = "Control|Shift"
key = "J"

[[keyboard.bindings]]
action = "Paste"
mods = "Shift"
key = "Insert"

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/fish"

[window]
decorations = "none"
dynamic_title = false
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
