export PATH=$PATH:"$HOME/bin"
export LANG=en_US.UTF-8
export NOTEDIR="/d/notes"

git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
PS1_origin=$PS1
PS1='\[\033[01;34m\]\W\[\033[33m\]$(git_branch)\[\033[00;32m\]\$\[\033[00m\] '

# load ble.sh
# source ~/.local/share/blesh/ble.sh

if [[ -f $HOME/.bash_aliases ]]; then
    . $HOME/.bash_aliases
fi
