[options]
SortBy = popularity
BottomUp = true
SudoLoop = true
SkipReview = true
CleanAfter = true
KeepSrc = false
Provides = yes
CombinedUpgrade = true
BatchInstall = true

[bin]
#FileManager =
#MFlags =
#Sudo =
