#!/bin/bash
# setup dpi
xrdb -merge ~/.Xresources
# disable bell
xset -b
# disable DPMS-Display Power Management Signaling
xset -dpms
xset s off
eval $(/usr/bin/ssh-agent)
xmodmap ~/.Xmodmap
# set windows compositor and wallpaper
picom --backend glx --vsync &
feh --bg-fill ~/Pictures/wallpaper/Dresden.jpg &
# get weather
weather.sh &
# set status bar
status_right.sh &
# fcitx5
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
fcitx5 -d --verbose 3 &
# notification manager
dunst &
# auto hide cursor
unclutter --ignore-buttons 4,5,6,7 --hide-on-touch --timeout 6 &
# start clash proxy
clash -d ~/.config/clash &
exec dwm
