#!/bin/bash
set -b
# set timeout to 0(never) and disable screen saver
xset dpms 0 0 0
xset s off
xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap
picom --daemon
# custom bin path
export PATH="$HOME/.local/share/flatpak/exports/bin:$PATH"
export PATH="$HOME/.local/share/jetbrains_toolbox/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# fcitx5 env
export INPUT_METHOD=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
# ensure mpc or ncmpcpp get correct socket
export MPD_HOST="$HOME/.config/mpd/socket"
# for dunst running by user systemd
systemctl --user import-environment DISPLAY XAUTHORITY
fcitx5 -d --verbose 3
flameshot &
feh --bg-fill ~/Pictures/wallpaper/defaultbg.jpg &
unclutter --ignore-buttons 4,5,6,7 --fork
status_right.sh &
exec dwm
