#!/bin/bash
set -b
xset -dpms
xset s off
xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap
# custom bin path
export PATH="$HOME/.local/share/flatpak/exports/bin:$PATH"
export PATH="$HOME/.local/share/jetbrains_toolbox/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# fcitx5
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
fcitx5 -d --verbose 3
weather.sh &
status_right.sh &
dunst &
clash -d ~/.config/clash &
feh --bg-fill ~/Pictures/wallpaper/defaultwall.jpg &
picom &
unclutter --ignore-buttons 4,5,6,7 --fork
exec dwm
