# 1. clone Iosevka repo:`git clone --depth 1 https://github.com/be5invis/Iosevka.git`
# 2. go to repo run `npm install`
# 3. create file private-build-plans.toml and copy content below
# 4. compile with ttf `npm run build -- ttf-unhinted::IosevkaZeng`
# 5. run `npm run build -- ttf::IosevkaZeng` with hinted font
[buildPlans.IosevkaZeng]
family = "IosevkaZeng"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.IosevkaZeng.variants.design]
two = "straight-neck-serifless"
eight = "two-circles"
zero = "slashed"
capital-d = "standard-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-q = "crossing"
capital-w = "straight-almost-flat-top-serifless"
w = "straight-almost-flat-top-serifless"
asterisk = "hex-mid"
number-sign = "slanted"
at = "compact"
dollar = "through-cap"
percent = "rings-continuous-slash"

[buildPlans.IosevkaZeng.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaZeng.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaZeng.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaZeng.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaZeng.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaZeng.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"
