vim9script
# variables must add white space between =; but set must not
set nocompatible
g:skip_defaults_vim = 1
filetype plugin indent on
syntax off
language en_US.UTF-8
&t_SI = "\<Esc>[6 q"
&t_SR = "\<Esc>[4 q"
&t_EI = "\<Esc>[2 q"
set encoding=utf-8
set hidden
set number
set relativenumber
set backspace=2
set textwidth=0
set incsearch
set ignorecase
set smartcase
set tabstop=4 shiftwidth=4 expandtab smartindent autoindent shiftround
set softtabstop=4
set showcmd
set laststatus=2
set wildmenu
set wildoptions=pum,tagfile
set showmatch
set autoread
set autowrite
set confirm
set updatetime=100
set noundofile
set nobackup
set clipboard^=unnamed,unnamedplus
set shortmess+=c
set hlsearch
set mouse=n
set mousehide
set signcolumn=yes
set cursorline
set cursorlineopt=number
set wrap
set linebreak
set cmdheight=1
set splitbelow
set splitright
set showtabline=1
set scrolloff=10
# Do not recognize octal numbers for Ctrl-A and Ctrl-X, most users find it  confusing.
set nrformats-=octal

inoremap jk <esc>
# quit
# use <Esc> instead of <M- keybind
nnoremap <leader>q :x<CR>
# close current or buffer
nnoremap <Space>b :bd<CR>
# yank whole buffer
nnoremap gy :%y<CR>
nnoremap gl ^yg_
# use backspace to scroll up/down
nnoremap <silent><C-j> <C-f>
nnoremap <silent><C-k> <C-b>
# save
nnoremap <silent><Enter> :w<CR>
# go next buffer
nnoremap <C-n> :bn<CR>
nnoremap <C-p> :b#<CR>
# window manage
nnoremap <Esc>j <C-w>j
nnoremap <Esc>k <C-w>k
nnoremap <Esc>h <C-w>h
nnoremap <Esc>l <C-w>l
# close window
nnoremap <Esc>w <C-w>c
nnoremap <Esc>o <C-w>o
nnoremap <leader>- <C-w>s
nnoremap <leader>/ <C-w>v
# quickfix list navigation
nnoremap ]q :cnext<CR>
nnoremap [q :cprev<CR>
nnoremap [Q :cfirst<CR>
nnoremap ]Q :clast<CR>
autocmd FileType tags,qf nnoremap <buffer> <Enter> <Enter>

# use rg in vim
if executable("rg")
  set grepprg=rg\ --vimgrep\ --smart-case\ --no-heading
  set grepformat=%f:%l:%c:%m
  nnoremap <leader>f :FZF<CR>
  nnoremap <leader>g :RG<CR>
  nnoremap <leader>b :Buffers<CR>
endif

set termguicolors
set background=dark
colorscheme retrobox
hi Normal guibg=NONE ctermbg=NONE guifg=LightGray gui=NONE
hi SignColumn guibg=NONE
# hi StatusLineNC guifg=#212529 guibg=Gray gui=NONE
hi StatusLine guifg=DarkGray guibg=#212529 gui=NONE ctermbg=NONE
hi CursorLineNr guifg=#ebcb8b guibg=NONE cterm=bold
hi VertSplit guibg=NONE guifg=#ebcb8b
set statusline=\ %w%f\ %h%m%r%=%-y%8P%16(%l,%c/%L%)

autocmd VimEnter * set formatoptions-=o textwidth=0
autocmd VimEnter *.log set filetype=log
autocmd FileType vim,javascript,typescript,lua,log set tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType markdown,text,log nnoremap <silent> j gj
autocmd FileType markdown,text,log nnoremap <silent> k gk

# restore cursor position
autocmd BufReadPost *
    | if line("'\"") >= 1 && line("'\"") <= line("$") && &filetype !~# 'commit' && index(['xxd', 'gitrebase'], &filetype) == -1
    | execute "normal! g`\""
    | endif


# commands
command! MakeTags !ctags -R .
command! Reloadrc source ~/.vimrc
command! Editrc edit ~/.vimrc

# netrw config
g:netrw_usetab = 1
g:netrw_browse_split = 0
g:netrw_altv = 1
g:netrw_liststyle = 3
nnoremap <Tab> :Lexplore<CR>

# tmux-vim navigator plugin
g:tmux_navigator_no_mappings = 1
noremap <silent><Esc>h :<C-U>TmuxNavigateLeft<cr>
noremap <silent><Esc>j :<C-U>TmuxNavigateDown<cr>
noremap <silent><Esc>k :<C-U>TmuxNavigateUp<cr>
noremap <silent><Esc>l :<C-U>TmuxNavigateRight<cr>
noremap <silent><Esc>p :<C-U>TmuxNavigatePrevious<cr>
