vim9script
# basic {{{
set nocompatible
g:skip_defaults_vim = 1
filetype plugin indent on
syntax on
set encoding=utf-8
$LANG = 'en_US'
set hidden
set number
set relativenumber
set backspace=2
set incsearch
set ignorecase
set smartcase
set tabstop=4 shiftwidth=4 expandtab smartindent autoindent shiftround
set softtabstop=4
set cindent
set showcmd
set laststatus=2
set completeopt+=popup
set wildmode=list:longest,full
set wildmenu
set wildoptions=pum
set showmatch
set autoread
set autowrite
set confirm
set updatetime=100
set noswapfile
set nobackup
set noundofile
set clipboard=unnamedplus
set hlsearch
set mouse=
set mousehide
set cursorline
set splitright
set splitbelow
set textwidth=0
set timeoutlen=1000
set ttimeoutlen=5
set shortmess-=S
set textwidth=0
set noshowmode
set novisualbell
set belloff=all
set t_vb=
if has("gui_running")
  set guicursor+=a:blinkon0
  set guifont=JetBrainsMonoNL\ NFM\ Light:h13
  set guioptions-=m
  set guioptions-=T
  set guioptions-=L
  set guioptions-=r
  # Maximize gvim window (for an alternative on Windows, see simalt below).
  autocmd GUIEnter * simalt ~x
else
  g:everforest_transparent_background = 2
endif
# }}}
# keymaps {{{
nnoremap <Enter> :w<CR>
nnoremap <silent><C-s> :wa<CR>
nnoremap <leader>` g~iw
vnoremap <leader>` g~
nnoremap <silent><C-n> :bn<CR>
nnoremap <nowait><C-p> :b#<CR>
nnoremap <silent><nowait><leader>q :xa<CR>
nnoremap <silent><nowait><space>b :bd<CR>
nnoremap <silent><leader>- :sp<CR>
nnoremap <silent><leader>/ :vs<CR>
nnoremap <leader>cd :cd %:p:h<CR>:pwd<CR>
nnoremap <C-j> <C-f>
nnoremap <C-k> <C-b>
nnoremap gy :%y<CR>
nnoremap gl ^yg_
nnoremap <silent><M-w> <C-w>c
nnoremap <silent><M-o> <C-w>o
nnoremap ]q :cnext<CR>
nnoremap [q :cprev<CR>
nnoremap ]Q :clast<CR>
nnoremap [Q :cfirst<CR>
nnoremap <space>s g<C-]>
nnoremap g_ ^vg_
# insert mode keymap
inoremap jk <ESC>
inoremap <C-e> <Esc>A
inoremap <C-s> <Esc>I
inoremap <C-a> <Esc>gI
# delete other buffers {{{
nnoremap <silent> <space>o :BufOnly<CR>
command! -nargs=? -complete=buffer -bang BufOnly {
  g:BufOnly('<args>', '<bang>')
}
def g:BufOnly(b: string, bang: string): void
  var buffer: number

  if b == ''
    # No buffer provided, use the current buffer.
    buffer = bufnr('%')
  elseif str2nr(b) > 0
    # A buffer number was provided.
    buffer = bufnr(str2nr(b))
  else
    # A buffer name was provided.
    buffer = bufnr(b)
  endif

  if buffer == -1
    echohl ErrorMsg
    echomsg 'No matching buffer for ' .. b
    echohl None
    return
  endif

  var last_buffer: number = bufnr('$')

  var delete_count = 0

  for n in range(1, last_buffer)
    if n != buffer && buflisted(n)
      if bang == '' && getbufvar(n, '&modified')
        echohl ErrorMsg
        echomsg 'No write since last change for buffer ' ..
        n .. ' (add ! to override)'
        echohl None
      else
        silent exe 'bdel' .. bang .. ' ' .. n
        if ! buflisted(n)
          ++delete_count
        endif
      endif
    endif
  endfor

  if delete_count == 1
    echomsg delete_count .. " buffer deleted"
  elseif delete_count > 1
    echomsg delete_count .. " buffers deleted"
  endif

enddef
# }}}
# }}}
# command {{{
command! Reloadrc source ~/.vimrc
command! Editrc edit ~/.vimrc
command! Fname echomsg expand('%:p') | setreg('+', expand('%:p'))
command! Rname echomsg expand('%') | setreg('+', expand('%'))
command! Tname echomsg expand('%:t') | setreg('+', expand('%:t'))
command! -nargs=1 S @/ = <q-args>
# }}}
# plugins {{{
var plugin_path = "~/.vim/plugins"
var plugin_manager = "~/.vim/plug.vim"
execute 'source' plugin_manager
call plug#begin(fnameescape(plugin_path))
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'justinmk/vim-sneak'
Plug 'junegunn/vim-easy-align'
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle'}
Plug 'junegunn/fzf',
Plug 'junegunn/fzf.vim',
Plug 'romainl/vim-cool'
Plug 'Eliot00/auto-pairs'
Plug 'ap/vim-buftabline'
Plug 'sainnhe/everforest'
call plug#end()
# NERDTreeToggle {{{
g:NERDTreeMinimalUI = 1
g:NERDTreeQuitOnOpen = 3
g:NERDTreeCaseSensitiveFS  =  1
g:NERDTreeShowLineNumbers = 1
g:NERDTreeWinSize = 40
g:NERDTreeIgnore = [
  '\.lock$[[file]]', '\.o$[[file]]', '\.out$[[file]]', '\.class$[[file]]', '\.exe$[[file]]', '\.bin$[[file]]', '\.svg$[[file]]', '\.png$[[file]]', '\.jpg$[[file]]',
  '^node_modules$[[dir]]', '^dist$[[dir]]', '^packages$[[dir]]', '^target$[[dir]]', '^lib$[[dir]]'
]
nnoremap <silent><nowait><Tab> :NERDTreeToggle<CR>
nnoremap <silent><nowait><C-s> :NERDTreeFind<CR>
# }}}
# buftabline {{{
g:buftabline_show = 1
g:buftabline_indicators = 1
g:buftabline_numbers = 2
nmap <nowait><Space>1 <Plug>BufTabLine.Go(1)
nmap <nowait><Space>2 <Plug>BufTabLine.Go(2)
nmap <nowait><Space>3 <Plug>BufTabLine.Go(3)
nmap <nowait><Space>4 <Plug>BufTabLine.Go(4)
nmap <nowait><Space>5 <Plug>BufTabLine.Go(5)
nmap <nowait><Space>6 <Plug>BufTabLine.Go(6)
nmap <nowait><Space>7 <Plug>BufTabLine.Go(7)
nmap <nowait><Space>8 <Plug>BufTabLine.Go(8)
nmap <nowait><Space>9 <Plug>BufTabLine.Go(9)
nmap <nowait><Space>0 <Plug>BufTabLine.Go(10)
# }}}
# auto-pair {{{
g:AutoPairsCenterLine = 0
g:AutoPairsShortcutToggle = '<M-}>'
#}}}
# fzf {{{
g:fzf_preview_window = []
nnoremap <Leader>f :FZF<CR>
nnoremap <Leader>g :RG<CR>
nnoremap <Leader>b :Buffers<CR>
# }}}
# theme {{{
set termguicolors
set background=dark
g:everforest_better_performance = 1
g:everforest_enable_italic = 0
colorscheme everforest
# }}}
# }}}
# autocmd {{{
&t_SI = "\<Esc>[6 q"
&t_SR = "\<Esc>[4 q"
&t_EI = "\<Esc>[2 q"
autocmd FileType gitcommit set textwidth=0
autocmd FileType * set formatoptions-=o
autocmd FileType javascript,html,vim,json,text,typescript,lua setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType markdown setlocal foldlevel=6
autocmd FileType xml setlocal nowrap
autocmd FileType vim setlocal foldmethod=marker
autocmd FileType json,javascript,java,go,python setlocal nowrap
autocmd FileType nerdtree setlocal wrap
autocmd FileType tags,qf nnoremap <buffer> <Enter> <Enter>
autocmd BufRead *.log setlocal filetype=log
autocmd BufRead *.painless setlocal filetype=java
autocmd BufRead *.xxd,*.hex setlocal filetype=xxd
# formatter
autocmd FileType json setlocal formatprg=jq
autocmd BufRead *.json,*.tmp nnoremap <nowait><silent> <Space>f :%!jq<CR>

# Remember the positions in files with some git-specific exceptions"
autocmd BufReadPost *
| if line("'\"") > 0 && line("'\"") <= line("$") && expand("%") !~ "ADD_EDIT.patch" && expand("%") !~ "addp-hunk-edit.diff" && index(['xxd', 'gitrebase', 'commit', 'gitcommit'], &filetype) == -1
  |     execute "normal! g`\""
  | endif

# clear syntax for file larger than 10000 lines
autocmd BufWinEnter * if line("$") >= 100000 | syntax clear | endif
# use less keymap for read-only buffers
autocmd BufEnter * ReadOnlyKeymap()
def ReadOnlyKeymap()
  if !&modifiable || &readonly
    nnoremap <buffer><nowait><silent>u <C-b>
    nnoremap <buffer><nowait><silent><Space> <C-f>
    nnoremap <buffer><nowait><silent>q :bd<CR>
  endif
enddef

# }}}
# statusline {{{
set statusline=\ %-5r%f%m%=%18(%l/%L%)%18(%{&fileformat}%Y%)%9(\ %{&fileencoding}%)
# }}}
# highlight {{{
hi link markdownError Normal
hi Folded ctermbg=NONE ctermfg=DarkGray
hi Comment ctermfg=DarkGray guifg=DarkGray cterm=NONE gui=NONE
hi Statusline cterm=bold gui=bold guifg=#587284 guibg=NONE
hi StatuslineNC gui=NONE guifg=#4c566a guibg=NONE
hi BufTabLineCurrent cterm=bold gui=bold guifg=lightgray guibg=#434c5e
hi BufTabLineHidden gui=NONE guifg=gray guibg=#2e3440
hi BufTabLineFill guibg=NONE guifg=NONE gui=NONE
hi TabLineFill guibg=NONE guifg=NONE
# }}}
