vim9script
# variables must add white space between =; but set must not
set nocompatible
g:skip_defaults_vim = 1
filetype plugin indent on
syntax on
language en_US.UTF-8
&t_SI = "\<Esc>[6 q"
&t_SR = "\<Esc>[4 q"
&t_EI = "\<Esc>[2 q"
set encoding=utf-8
set hidden
set number
set relativenumber
set backspace=2
set textwidth=0
set incsearch
set ignorecase
set smartcase
set tabstop=4 shiftwidth=4 expandtab smartindent autoindent shiftround
set softtabstop=4
set showcmd
set laststatus=2
set wildmenu
set wildoptions=pum,tagfile
set showmatch
set autoread
set autowrite
set confirm
set updatetime=100
set noundofile
set nobackup
set clipboard^=unnamed,unnamedplus
set shortmess-=S
set hlsearch
set mouse=n
set mousehide
set signcolumn=yes
set cursorline
# set cursorlineopt=number
set wrap
set linebreak
set cmdheight=1
set splitbelow
set splitright
set showtabline=1
set scrolloff=10
# Do not recognize octal numbers for Ctrl-A and Ctrl-X, most users find it  confusing.
set nrformats-=octal
set omnifunc=ccomplete#Complete
set tags=tags,~/.vim/system.tags

inoremap jk <esc>
# quit
# use <Esc> instead of <M- keybind
nnoremap <silent><nowait><leader>q :xa<CR>
# yank whole buffer
nnoremap gy :%y<CR>
# copy line content
nnoremap gl ^yg_
# remap page up/down
nnoremap <silent><nowait><C-j> <C-f>
nnoremap <silent><nowait><C-k> <C-b>
# save
nnoremap <silent><nowait><Enter> :w<CR>
# buffer keymaps
nnoremap <silent><nowait><Space>b :bd<CR>
nnoremap <silent><nowait><C-n> :bn<CR>
nnoremap <silent><nowait><C-p> :b#<CR>
# windows keymaps
nnoremap <silent><nowait><Esc>j <C-w>j
nnoremap <silent><nowait><Esc>k <C-w>k
nnoremap <silent><nowait><Esc>h <C-w>h
nnoremap <silent><nowait><Esc>l <C-w>l
nnoremap <silent><nowait><Esc>w <C-w>c
nnoremap <silent><nowait><Esc>o <C-w>o
nnoremap <silent><nowait><leader>- <C-w>s
nnoremap <silent><nowait><leader>/ <C-w>v
# quickfix list navigation
nnoremap <silent><nowait>]q :cnext<CR>
nnoremap <silent><nowait>[q :cprev<CR>
nnoremap <silent><nowait>[Q :cfirst<CR>
nnoremap <silent><nowait>]Q :clast<CR>
autocmd FileType tags,qf nnoremap <buffer> <Enter> <Enter>

# use rg in vim
if executable("rg")
  set grepprg=rg\ --vimgrep\ --smart-case\ --no-heading
  set grepformat=%f:%l:%c:%m
  nnoremap <silent><nowait><leader>f :FZF<CR>
  nnoremap <silent><nowait><leader>g :RG<CR>
  nnoremap <silent><nowait><leader>b :Buffers<CR>
endif

set termguicolors
set background=dark
colorscheme habamax
hi Normal guibg=NONE ctermbg=NONE guifg=LightGray gui=NONE
hi SignColumn guibg=NONE
hi StatusLine guibg=DarkGray guifg=#2d2d2d gui=bold cterm=bold
hi StatusLineNC guifg=#252525 guibg=#666666 gui=NONE
hi CursorLineNr guifg=#ebcb8b guibg=NONE
hi LineNr guifg=DarkGray
hi VertSplit guibg=NONE guifg=#888888
set statusline=%-5r%f\ %m%=%-10(%{&fileformat}%Y%)%16(%l/%L%)

autocmd VimEnter * set formatoptions-=o textwidth=0
autocmd VimEnter *.log set filetype=log
def SetViewKeymap()
  if !&modifiable || &readonly
    nnoremap <buffer><nowait><silent> u <C-b>
    nnoremap <buffer><nowait><silent> <Space> <C-f>
    nnoremap <buffer><nowait><silent> q :bd<CR>
  endif
enddef
autocmd BufEnter * SetViewKeymap()

def SetVirtualMap()
  nnoremap <silent><nowait> j gj
  nnoremap <silent><nowait> k gk
enddef
autocmd FileType markdown,text,log SetVirtualMap()
autocmd FileType vim,javascript,typescript,lua,log set tabstop=2 shiftwidth=2 softtabstop=2

# restore cursor position
autocmd BufReadPost *
    | if line("'\"") >= 1 && line("'\"") <= line("$") && &filetype !~# 'commit' && index(['xxd', 'gitrebase'], &filetype) == -1
    | execute "normal! g`\""
    | endif


# commands
command! MakeTags !ctags -R .
command! Reloadrc source ~/.vimrc
command! Editrc edit ~/.vimrc

# netrw config
g:netrw_usetab = 1
g:netrw_browse_split = 0
g:netrw_altv = 1
g:netrw_liststyle = 3
nnoremap <Tab> :Explore<CR>

# tmux-vim navigator plugin
g:tmux_navigator_no_mappings = 1
noremap <nowait><silent><Esc>h :<C-U>TmuxNavigateLeft<cr>
noremap <nowait><silent><Esc>j :<C-U>TmuxNavigateDown<cr>
noremap <nowait><silent><Esc>k :<C-U>TmuxNavigateUp<cr>
noremap <nowait><silent><Esc>l :<C-U>TmuxNavigateRight<cr>
noremap <nowait><silent><Esc>p :<C-U>TmuxNavigatePrevious<cr>
