# default volume
volume=100
# Don't allow new windows to be larger than the screen.
autofit-larger=100%x100%
# Enable hardware decoding if available, =yes is implied.
hwdec
# start from last position
save-position-on-quit=yes
# one line subtitle
sub-single=true
# set subtitle font style
sub-font="Helvetica"
sub-color="#EBCB8B"
