resume-playback
# default volume
volume=50
# Don't allow new windows to be larger than the screen.
autofit-larger=100%x100%
# use VA-API for Intel GPU
hwdec=vaapi
# start from last position
save-position-on-quit=yes
# set subtitle font style
sub-font="NotoSansMix"
sub-color="#EBCB8B"
# for network stream
ytdl-raw-options="cookies-from-browser=firefox"
