Section "InputClass"
    Identifier "touchpad catchall"
    MatchDevicePath "/dev/input/event5"
    Driver "libinput"
    Option "Tapping" "on"
    Option "NaturalScrolling" "true"
    Option "Natural Scrolling" "true"
EndSection
