alias l="ls -lh"
if [ -x "/usr/bin/exa" ]; then
    unalias l
    alias l="exa --long --links --sort=name --git"
fi
alias la="ls -lAh"
alias cls="clear"
alias ..="cd .."
# git aliaes
alias gst="git status"
alias gad="git add"
alias gdf="git diff"
alias gcm="git commit -am"
alias gps="git push"
alias gpl="git pull"
# vim and neovim
alias vi="/usr/bin/vim"
alias vim="/usr/local/bin/nvim"
alias bat="batcat"
alias note="joplin"

# temp
alias cdwin="cd /media/zeng/30C653FCC653C0B0"
