alias l="ls -lh"
alias la="ls -lAh"
if [ -x "/usr/bin/exa" ]; then
    unalias l
    unalias la
    alias l="exa --long --links --sort=name --git"
    alias la="exa -l --color always --icons --git -a -s type"
fi
alias cls="clear"
alias ..="cd .."
# git aliaes
alias gst="git status"
alias gad="git add"
alias gdf="git diff"
alias gcm="git commit -am"
alias gps="git push"
alias gpl="git pull"
# vim and neovim
alias vi="/usr/bin/vim"
alias vim="nvim"
alias bat="batcat"
